server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://43.143.239.152:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: ncl@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  redis:
    host: 43.143.239.152
    port: 6379

mybatis:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml
logging:
  level:
    com.health.Mapper: debug


